### ISSUE TITLE
[BUG] exportVariable crashes

### ISSUE THREAD

**Issue by passsy** [dkrutskikh/actions-toolkit-dart#22]
```dart
import 'package:actions_toolkit_dart/core.dart' as gha;

main() {
  gha.exportVariable(name: 'FOO', value: 'bar');
}
```

```text
Unsupported operation: Cannot modify unmodifiable map
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269)
#1      exportVariable (package:actions_toolkit_dart/src/core/core.dart:18)
#2      BuildIosCommand.run (package:iv_sidekick/src/commands/build_commands/build_ios_command.dart:48)
#3      CommandRunner.runCommand (package:args/command_runner.dart:209)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119)
#5      new Future.sync (dart:async/future.dart:301)
#6      CommandRunner.run (package:args/command_runner.dart:119)
#7      SidekickCommandRunner.run (package:sidekick_core/sidekick_core.dart:92)
#8      runIv (package:iv_sidekick/iv_sidekick.dart:48)
#9      main (file:///Users/pascalwelsch/Projects/vodafone/invo-frontend/packages/iv_sidekick/bin/main.dart:4)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

Reproducible with `0.4.0`. Either Dart changed `Platform.environment` to be unmodifiable recently or it never worked

**Comment by dkrutskikh** [comment]
@passsy good catch! Fixed in `0.4.1` version. I'll close this issue, fell free to reopen if problem not fully fixed.

**Comment by passsy** [comment]
Thanks for the fast update!

I now get the error with `0.4.1`

```
Invalid argument(s): Missing file at path: /Users/runner/work/_temp/_runner_file_commands/set_env_6c0c95c2-5178-4599-8b3f-97a41170dcb7
#0      issueFileCommand (package:actions_toolkit_dart/src/core/file_command.dart:16)
#1      exportVariable (package:actions_toolkit_dart/src/core/core.dart:25)
```

**Comment by dkrutskikh** [comment]
@passsy can you provide more details about your current problem?
